restart::
	sudo forever stop 6004x_server.js; sudo forever start -l server.log -a -o server.out -e server.err 6004x_server.js

stop::
	sudo forever stop 6004x_server.js

start::
	sudo forever start -l server.log -a -o server.out -e server.err 6004x_server.js
