restart::
	sudo forever stop queue.js; sudo forever start -l server.log -a -o server.out -e server.err queue.js

stop::
	sudo forever stop queue.js

start::
	sudo forever start -l server.log -a -o server.out -e server.err queue.js
